blockbook-testnet:
  build: .
  dockerfile: Dockerfile
  #image: christroutner/blockbook-0.3.2-bch-testnet
  container_name: blockbook-testnet
  ports:
    - "19031:9030"
    - "19131:9130"
  volumes:
    #- ../data:/opt/coins/data/bcash/blockbook/db
    - /mnt/data/bitcoin.com/blockchain-data/blockbook-testnet/data:/opt/coins/data/bcash/blockbook/db
    - ../logs:/opt/coins/blockbook/bcash/logs
  restart: always
