blockbook-node:
  build: .
  dockerfile: Dockerfile
  container_name: blockbook
  ports:
    - "9031:9030"
    - "9131:9130"
  volumes:
    - ../data:/opt/coins/data/bcash/blockbook/db
    - ../logs:/opt/coins/blockbook/bcash/logs
  restart: always
