bitcore-node:
  build: .
  dockerfile: Dockerfile
  container_name: blockbook-testnet
  ports:
    - "19031:9030"
    - "19131:9130"
  volumes:
    - ../data:/opt/coins/data/bcash/blockbook/db
    - ../logs:/opt/coins/blockbook/bcash/logs
  restart: always
