blockbook-node:
  #build: .
  #dockerfile: Dockerfile
  image: christroutner/blockbook-0.3.2-bch-mainnet
  container_name: blockbook
  ports:
    - "9031:9030"
    - "9131:9130"
  volumes:
    - /mnt/data/bitcoin.com/blockchain-data/blockbook-mainnet/data:/opt/coins/data/bcash/blockbook/db
    - ../logs:/opt/coins/blockbook/bcash/logs
  restart: always
